/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.permintaan;

import id.ac.unpas.techIn.permintaan.*;
import java.util.List;
import javax.swing.JTextField;
import id.ac.unpas.techIn.dao.PermintaanDao;
import id.ac.unpas.techIn.frame.PermintaanFrame;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.plaf.basic.BasicScrollBarUI;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author ghifarullah19
 */
public class CardPermintaan
        extends javax.swing.JFrame {
    
    // jenisMemberList adalah variabel yang digunakan untuk menyimpan data jenis member
    private List<Permintaan> permintaanList;
    
    // jenisMemberDao adalah variabel yang digunakan untuk menyimpan data jenis member yang didapat dari database
    private PermintaanDao permintaanDao;

    /**
     * Creates new form PermintaanFrame2
     */
    public CardPermintaan(PermintaanDao permintaanDao) {
        // this.jenisMemberDao diberikan nilai dari parameter jenisMemberDao
        this.permintaanDao = permintaanDao;
        // this.jenisMemberList diberikan nilai dari data jenis member yang didapat dari database
        this.permintaanList = this.permintaanDao.findAll();
        
        initComponents();
        
        showPermintaanPane.setLayout(new BoxLayout(showPermintaanPane, BoxLayout.PAGE_AXIS));
        
        for (int i = 0; i < permintaanList.size(); i++) {
            PermintaanFrame permintaan = new PermintaanFrame();
            permintaan.setPanelData(permintaanList.get(i));
            showPermintaanPane.add(permintaan.getFrame());
        }
        
        showPermintaanScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        textFieldNama = new javax.swing.JTextField();
        textFieldAlamat = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();
        textFieldStatus = new javax.swing.JTextField();
        showPermintaanScrollPane = new javax.swing.JScrollPane();
        showPermintaanPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel2.setText("Permintaan Add");

        labelNama.setText("Nama");

        labelAlamat.setText("Alamat");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        textFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNamaActionPerformed(evt);
            }
        });

        textFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldAlamatActionPerformed(evt);
            }
        });

        labelStatus.setText("Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 458, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSimpan)
                    .addComponent(labelAlamat)
                    .addComponent(textFieldNama)
                    .addComponent(textFieldAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(labelNama)
                    .addComponent(labelStatus)
                    .addComponent(textFieldStatus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSimpan)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add", jPanel2);

        javax.swing.GroupLayout showPermintaanPaneLayout = new javax.swing.GroupLayout(showPermintaanPane);
        showPermintaanPane.setLayout(showPermintaanPaneLayout);
        showPermintaanPaneLayout.setHorizontalGroup(
            showPermintaanPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        showPermintaanPaneLayout.setVerticalGroup(
            showPermintaanPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        showPermintaanScrollPane.setViewportView(showPermintaanPane);

        jTabbedPane1.addTab("Show", showPermintaanScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNamaActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        // Variable nama untuk menyimpan nilai dari objek textFieldNama (nama)
        String nama = this.textFieldNama.getText();
        // Variable alamat untuk menyimpan nilai dari objek txtOutput (alamat)
        String alamat = this.textFieldAlamat.getText();// Variable alamat untuk menyimpan nilai dari objek txtOutput (alamat)
        String tempStatus = this.textFieldStatus.getText();

        boolean status = false;
        
        if (tempStatus.equalsIgnoreCase("1")) {
            status = true;
        }
        
        // Instansiasi objek biodata dengan nama biodata
        Permintaan permintaan = new Permintaan();

        // Set nama biodata dengan nilai dari variable nama
        permintaan.setNama(nama);
        // Set alamat biodata dengan nilai dari variable alamat
        permintaan.setAlamat(alamat);
        permintaan.setStatus(status);

        this.permintaanDao.insert(permintaan);
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void textFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAlamatActionPerformed

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel showPermintaanPane;
    private javax.swing.JScrollPane showPermintaanScrollPane;
    private javax.swing.JTextField textFieldAlamat;
    private javax.swing.JTextField textFieldNama;
    private javax.swing.JTextField textFieldStatus;
    // End of variables declaration//GEN-END:variables
}
