/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.permintaan;

import id.ac.unpas.techIn.permintaan.Permintaan;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ghifarullah19
 */
public class PermintaanCard
        extends javax.swing.JFrame {

    /**
     * Creates new form PermintaanFrame
     */
    public PermintaanCard() {
        initComponents();
        
    }
    
    public JPanel getFrame() {
        return this.permintaanPanel;
    }
    
    public void setPanelData(Permintaan pelanggan) {
        namaKurir.setText(pelanggan.getNama());
        alamatPenjemputan.setText(pelanggan.getAlamat());
        
        iconMaps.setText("");
        iconMaps.setIcon(imageIcon("C:\\Users\\ghifarullah19\\Documents\\NetBeansProjects\\tech-in\\src\\main\\java\\id\\ac\\unpas\\techIn\\img\\maps.png",
                70,
                70));
        
        if (pelanggan.getStatus()) {
            iconStatus.setText("");
            iconStatus.setIcon(imageIcon("C:\\Users\\ghifarullah19\\Documents\\NetBeansProjects\\tech-in\\src\\main\\java\\id\\ac\\unpas\\techIn\\img\\my-svg.png",
                    26,
                    26));
        } else {
            buttonDetail.setText("Menunggu");
            buttonDetail.setBackground(Color.red);
            iconStatus.setText("");
            iconStatus.setIcon(imageIcon("C:\\Users\\ghifarullah19\\Documents\\NetBeansProjects\\tech-in\\src\\main\\java\\id\\ac\\unpas\\techIn\\img\\my-svg-red.png",
                    26,
                    26));
        }
    }
    
    public ImageIcon imageIcon(String imageURL, int height, int width) {
        ImageIcon icon = new ImageIcon(imageURL);
        Image image = icon.getImage();
        Image newImage = image.getScaledInstance(width,
                        height,
                        Image.SCALE_SMOOTH);
        icon = new ImageIcon(newImage);
        return icon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jPanel2 = new javax.swing.JPanel();
        jOptionPane1 = new javax.swing.JOptionPane();
        permintaanPanel = new javax.swing.JPanel();
        buttonDetail = new javax.swing.JButton();
        namaKurir = new javax.swing.JLabel();
        alamatPenjemputan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        iconMaps = new javax.swing.JLabel();
        iconStatus = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        permintaanPanel.setBackground(new java.awt.Color(255, 255, 255));
        permintaanPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        permintaanPanel.setForeground(new java.awt.Color(0, 102, 204));
        permintaanPanel.setMaximumSize(new java.awt.Dimension(556, 131));

        buttonDetail.setBackground(new java.awt.Color(0, 204, 0));
        buttonDetail.setForeground(new java.awt.Color(255, 255, 255));
        buttonDetail.setText("Detail");
        buttonDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDetailActionPerformed(evt);
            }
        });

        namaKurir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaKurir.setForeground(new java.awt.Color(0, 102, 204));
        namaKurir.setText("namaKurir");

        alamatPenjemputan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alamatPenjemputan.setForeground(new java.awt.Color(0, 102, 204));
        alamatPenjemputan.setText("alamatPenjemputan");

        iconMaps.setText("iconMaps");

        iconStatus.setText("status");

        javax.swing.GroupLayout permintaanPanelLayout = new javax.swing.GroupLayout(permintaanPanel);
        permintaanPanel.setLayout(permintaanPanelLayout);
        permintaanPanelLayout.setHorizontalGroup(
            permintaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(permintaanPanelLayout.createSequentialGroup()
                .addGroup(permintaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(permintaanPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(alamatPenjemputan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 385, Short.MAX_VALUE)
                        .addComponent(buttonDetail))
                    .addGroup(permintaanPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(namaKurir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        permintaanPanelLayout.setVerticalGroup(
            permintaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(permintaanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(permintaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(namaKurir)
                    .addComponent(iconStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(permintaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iconMaps, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alamatPenjemputan)
                    .addComponent(buttonDetail))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(permintaanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(permintaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PermintaanCard.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PermintaanCard.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PermintaanCard.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PermintaanCard.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PermintaanCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatPenjemputan;
    private javax.swing.JButton buttonDetail;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel iconMaps;
    private javax.swing.JLabel iconStatus;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel namaKurir;
    private javax.swing.JPanel permintaanPanel;
    // End of variables declaration//GEN-END:variables
}
