/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.riwayat;

import id.ac.unpas.techIn.riwayat.*;
import java.util.List;
import id.ac.unpas.techIn.dao.RiwayatDao;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author ghifarullah19
 */
public class RiwayatFrame
        extends javax.swing.JFrame {
    
    // jenisMemberList adalah variabel yang digunakan untuk menyimpan data jenis member
    private List<Riwayat> riwayatList;
    
    // jenisMemberDao adalah variabel yang digunakan untuk menyimpan data jenis member yang didapat dari database
    private RiwayatDao riwayatDao;

    /**
     * Creates new form PermintaanFrame2
     */
    public RiwayatFrame(RiwayatDao riwayatDao) {
        // this.jenisMemberDao diberikan nilai dari parameter jenisMemberDao
        this.riwayatDao = riwayatDao;
        // this.jenisMemberList diberikan nilai dari data jenis member yang didapat dari database
        this.riwayatList = this.riwayatDao.findAll();
        
        initComponents();
        
//        showPermintaanPane.setLayout(new BoxLayout(showPermintaanPane, BoxLayout.PAGE_AXIS));
        showRiwayatPane.setLayout(new GridLayout(riwayatList.size(), 1, 0, 10));
        
        for (int i = 0; i < riwayatList.size(); i++) {
            JPanel panel = new JPanel();
            RiwayatCard riwayat = new RiwayatCard();
            riwayat.setPanelData(riwayatList.get(i));
            panel.setBackground(new Color(0,0,0,0));
            panel.add(riwayat.getFrame());
            showRiwayatPane.add(panel);
        }
        showRiwayatScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRiwayat = new javax.swing.JPanel();
        panelTitleRiwayat = new javax.swing.JPanel();
        labelTitleRiwayat = new javax.swing.JLabel();
        showRiwayatScrollPane = new javax.swing.JScrollPane();
        showRiwayatPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRiwayat.setBackground(new java.awt.Color(155, 190, 200));

        panelTitleRiwayat.setBackground(new java.awt.Color(66, 125, 157));

        labelTitleRiwayat.setFont(new java.awt.Font("Kaushan Script", 0, 12)); // NOI18N
        labelTitleRiwayat.setForeground(new java.awt.Color(255, 255, 255));
        labelTitleRiwayat.setText("Riwayat ");

        javax.swing.GroupLayout panelTitleRiwayatLayout = new javax.swing.GroupLayout(panelTitleRiwayat);
        panelTitleRiwayat.setLayout(panelTitleRiwayatLayout);
        panelTitleRiwayatLayout.setHorizontalGroup(
            panelTitleRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleRiwayatLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTitleRiwayat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitleRiwayatLayout.setVerticalGroup(
            panelTitleRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleRiwayatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitleRiwayat)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        showRiwayatScrollPane.setBackground(new java.awt.Color(155, 190, 200));

        showRiwayatPane.setBackground(new java.awt.Color(155, 190, 200));

        javax.swing.GroupLayout showRiwayatPaneLayout = new javax.swing.GroupLayout(showRiwayatPane);
        showRiwayatPane.setLayout(showRiwayatPaneLayout);
        showRiwayatPaneLayout.setHorizontalGroup(
            showRiwayatPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        showRiwayatPaneLayout.setVerticalGroup(
            showRiwayatPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        showRiwayatScrollPane.setViewportView(showRiwayatPane);

        javax.swing.GroupLayout panelRiwayatLayout = new javax.swing.GroupLayout(panelRiwayat);
        panelRiwayat.setLayout(panelRiwayatLayout);
        panelRiwayatLayout.setHorizontalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitleRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showRiwayatScrollPane)
        );
        panelRiwayatLayout.setVerticalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRiwayatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelTitleRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showRiwayatScrollPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRiwayat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTitleRiwayat;
    private javax.swing.JPanel panelRiwayat;
    private javax.swing.JPanel panelTitleRiwayat;
    private javax.swing.JPanel showRiwayatPane;
    private javax.swing.JScrollPane showRiwayatScrollPane;
    // End of variables declaration//GEN-END:variables
}
