/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.pelanggan;

import id.ac.unpas.techIn.dao.PelangganDao;
import id.ac.unpas.techIn.pelanggan.Pelanggan;
import id.ac.unpas.techIn.penjemputan.Penjemputan;
import id.ac.unpas.techIn.pelanggan.PelangganModelTable;
import java.util.List;

/**
 *
 * @author ghifarullah19
 */
public class PelangganCRUD
        extends javax.swing.JFrame {
    
    private List<Pelanggan> pelangganList;
    private Pelanggan pelangganUbah;
    private PelangganDao pelangganDao;
    private PelangganModelTable pelangganModelTable;

    /**
     * Creates new form PelangganCRUD
     */
    public PelangganCRUD(PelangganDao pelangganDao) {
        this.pelangganDao = pelangganDao;
        this.pelangganList = this.pelangganDao.findAll();
        this.pelangganModelTable = new PelangganModelTable(pelangganList);
        
        initComponents();
        
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        frameCRUDPelanggan = new javax.swing.JPanel();
        panelCRUDPelanggan = new javax.swing.JPanel();
        labelNamaPelanggan = new javax.swing.JLabel();
        textfieldNamaPelanggan = new javax.swing.JTextField();
        labelAlamatPelanggan = new javax.swing.JLabel();
        textfieldAlamatPelanggan = new javax.swing.JTextField();
        titleCRUDPelanggan = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKirim = new javax.swing.JButton();
        buttonSimpanUbah = new javax.swing.JButton();
        scrollableTable = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameCRUDPelanggan.setBackground(new java.awt.Color(102, 153, 255));

        panelCRUDPelanggan.setBackground(new java.awt.Color(255, 255, 255));

        labelNamaPelanggan.setText("Nama Pelanggan");

        labelAlamatPelanggan.setText("Alamat");

        titleCRUDPelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCRUDPelanggan.setText("Form Pelanggan");

        buttonKembali.setText("Kembali");

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonKirim.setText("Kirim");
        buttonKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKirimActionPerformed(evt);
            }
        });

        buttonSimpanUbah.setText("Simpan Ubah");
        buttonSimpanUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDPelangganLayout = new javax.swing.GroupLayout(panelCRUDPelanggan);
        panelCRUDPelanggan.setLayout(panelCRUDPelangganLayout);
        panelCRUDPelangganLayout.setHorizontalGroup(
            panelCRUDPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCRUDPelangganLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleCRUDPelanggan)
                .addGap(164, 164, 164))
            .addGroup(panelCRUDPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCRUDPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCRUDPelangganLayout.createSequentialGroup()
                        .addComponent(buttonKembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimpanUbah))
                    .addGroup(panelCRUDPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelNamaPelanggan)
                        .addComponent(labelAlamatPelanggan)
                        .addComponent(textfieldAlamatPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(textfieldNamaPelanggan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonKirim)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelCRUDPelangganLayout.setVerticalGroup(
            panelCRUDPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleCRUDPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNamaPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAlamatPelanggan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldAlamatPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(panelCRUDPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKembali)
                    .addComponent(buttonUbah)
                    .addComponent(buttonHapus)
                    .addComponent(buttonKirim)
                    .addComponent(buttonSimpanUbah))
                .addGap(62, 62, 62))
        );

        tablePelanggan.setModel(pelangganModelTable);
        jScrollPane1.setViewportView(tablePelanggan);

        scrollableTable.setViewportView(jScrollPane1);

        javax.swing.GroupLayout frameCRUDPelangganLayout = new javax.swing.GroupLayout(frameCRUDPelanggan);
        frameCRUDPelanggan.setLayout(frameCRUDPelangganLayout);
        frameCRUDPelangganLayout.setHorizontalGroup(
            frameCRUDPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCRUDPelangganLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(frameCRUDPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCRUDPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollableTable, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        frameCRUDPelangganLayout.setVerticalGroup(
            frameCRUDPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCRUDPelangganLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelCRUDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollableTable, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameCRUDPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameCRUDPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKirimActionPerformed
        // TODO add your handling code here:
        
        String namaPelanggan = this.textfieldNamaPelanggan.getText();
        String alamatPenjemputan = this.textfieldAlamatPelanggan.getText();

        Pelanggan pelanggan = new Pelanggan();
        Penjemputan penjemputan = new Penjemputan();
        
        pelanggan.setNama(namaPelanggan);
        pelanggan.setAlamat(alamatPenjemputan);

        this.pelangganDao.insert(pelanggan);
        this.addData(pelanggan);
    }//GEN-LAST:event_buttonKirimActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        int row = tablePelanggan.getSelectedRow();
        int column = tablePelanggan.getSelectedColumn();

        if (row == -1 || column == -1) {
            return;
        }

        String dataUbah = (String) tablePelanggan.getModel().getValueAt(row, column);

        int id = -1;
        String col = "";

        switch (column) {
            case 0:
                col = "namaPelanggan";
                break;
            case 1:
                col = "alamatPenjemputan";
                break;
            case 2:
                col = "status";
                break;
            default:
                System.out.println("Kolom tidak ditemukan");
                break;
        }
        id = this.pelangganDao.select(col, dataUbah).getId();
       
        this.textfieldNamaPelanggan.setText(this.pelangganDao.select(col, dataUbah).getNama());
        this.textfieldAlamatPelanggan.setText(this.pelangganDao.select(col, dataUbah).getAlamat());

        
        pelangganUbah = new Pelanggan();
        pelangganUbah.setId(id);
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonSimpanUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanUbahActionPerformed
        // TODO add your handling code here:
        
        String nama = this.textfieldNamaPelanggan.getText();
        String alamat = this.textfieldAlamatPelanggan.getText();

        Pelanggan pelanggan = new Pelanggan();
        pelanggan.setId(pelangganUbah.getId());
        pelanggan.setNama(nama);
        pelanggan.setAlamat(alamat);

        this.pelangganDao.update(pelanggan);
        this.update(pelanggan);
    }//GEN-LAST:event_buttonSimpanUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int row = this.tablePelanggan.getSelectedRow();
        int column = this.tablePelanggan.getSelectedColumn();

        if (row == -1 || column == -1) {
          return;
        } else {
          String newValue = (String) this.tablePelanggan.getModel().getValueAt(row, column);
     
          Pelanggan id = new Pelanggan();

          String col = "";

          switch (column) {
                case 0:
                    col = "namaPelanggan";
                    break;
                case 1:
                    col = "alamatPenjemputan";
                    break;
                case 2:
                    col = "status";
                    break;
                default:
                    System.out.println("Kolom tidak ditemukan");
                    break;
            }
            id = this.pelangganDao.select(col, newValue);

            this.delete(id);
            this.pelangganDao.delete(id);
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    // Method untuk menambahkan pelanggan ke tableModel
    public void addData(Pelanggan pelanggan) {
        pelangganModelTable.add(pelanggan);
        textfieldNamaPelanggan.setText("");
        textfieldAlamatPelanggan.setText("");
    }
    
    // Method untuk mengubah pelanggan ke tableModel
    public void update(Pelanggan pelanggan) {
        pelangganModelTable.update(pelanggan);
        textfieldNamaPelanggan.setText("");
        textfieldAlamatPelanggan.setText("");
    }
    
    // Method untuk menghapus pelanggan ke tableModel
    public void delete(Pelanggan pelanggan) {
        // Tambahkan pelanggan ke tableModel
        pelangganModelTable.delete(pelanggan);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonKirim;
    private javax.swing.JButton buttonSimpanUbah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JPanel frameCRUDPelanggan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlamatPelanggan;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JPanel panelCRUDPelanggan;
    private javax.swing.JScrollPane scrollableTable;
    private javax.swing.JTable tablePelanggan;
    private javax.swing.JTextField textfieldAlamatPelanggan;
    private javax.swing.JTextField textfieldNamaPelanggan;
    private javax.swing.JLabel titleCRUDPelanggan;
    // End of variables declaration//GEN-END:variables
}
