/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.main;

import id.ac.unpas.techIn.dao.KurirDao;
import id.ac.unpas.techIn.dao.LacakDao;
import id.ac.unpas.techIn.dao.PelangganDao;
import id.ac.unpas.techIn.dao.PermintaanDao;
import id.ac.unpas.techIn.dao.PenjemputanDao;
import id.ac.unpas.techIn.kurir.Kurir;
import id.ac.unpas.techIn.lacak.LacakCRUD;
import id.ac.unpas.techIn.lacak.LacakFrame;
import id.ac.unpas.techIn.pelanggan.PelangganFrame;
import id.ac.unpas.techIn.penjemputan.PenjemputanFrame;
import id.ac.unpas.techIn.permintaan.PermintaanCRUD;
import id.ac.unpas.techIn.permintaan.PermintaanFrame;
import id.ac.unpas.techIn.kurir.KurirCRUD;
import id.ac.unpas.techIn.penjemputan.PenjemputanCRUD;
import id.ac.unpas.techIn.pelanggan.PelangganCRUD;
import java.util.List;

/**
 *
 * @author ghifarullah19
 */
public class MenuCRUD
        extends javax.swing.JFrame {

    private PelangganFrame pelangganFrame;
    private PermintaanFrame permintaanFrame;
    private PermintaanFrame penjemputanFrame;
    private LacakFrame lacakFrame;
    private PelangganDao pelangganDao;
    private PermintaanDao permintaanDao;
    private PermintaanDao penjemputanDao;
    private LacakDao lacakDao;

    /**
     * Creates new form MenuCRUD
     */
    public MenuCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCRUD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonPagePermintaan = new javax.swing.JButton();
        buttonPagePenjemputan = new javax.swing.JButton();
        buttonPageLacak = new javax.swing.JButton();
        buttonPageRiwayat = new javax.swing.JButton();
        buttonPageKurir = new javax.swing.JButton();
        buttonPagePelanggan = new javax.swing.JButton();
        buttonPageSampah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCRUD.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("MENU CRUD");

        buttonPagePermintaan.setText("Permintaan");
        buttonPagePermintaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagePermintaanActionPerformed(evt);
            }
        });

        buttonPagePenjemputan.setText("Penjemputan");
        buttonPagePenjemputan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagePenjemputanActionPerformed(evt);
            }
        });

        buttonPageLacak.setText("Lacak");
        buttonPageLacak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPageLacakActionPerformed(evt);
            }
        });

        buttonPageRiwayat.setText("Riwayat");

        buttonPageKurir.setText("Kurir");
        buttonPageKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPageKurirActionPerformed(evt);
            }
        });

        buttonPagePelanggan.setText("Pelanggan");
        buttonPagePelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPagePelangganActionPerformed(evt);
            }
        });

        buttonPageSampah.setText("Sampah");
        buttonPageSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPageSampahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDLayout = new javax.swing.GroupLayout(panelCRUD);
        panelCRUD.setLayout(panelCRUDLayout);
        panelCRUDLayout.setHorizontalGroup(
            panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(panelCRUDLayout.createSequentialGroup()
                        .addComponent(buttonPagePermintaan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonPagePenjemputan)
                        .addGap(18, 18, 18)
                        .addComponent(buttonPageLacak)
                        .addGap(18, 18, 18)
                        .addComponent(buttonPageRiwayat)))
                .addGap(18, 18, 18)
                .addComponent(buttonPageKurir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPagePelanggan)
                .addGap(18, 18, 18)
                .addComponent(buttonPageSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelCRUDLayout.setVerticalGroup(
            panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCRUDLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(panelCRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPagePermintaan)
                    .addComponent(buttonPagePenjemputan)
                    .addComponent(buttonPageLacak)
                    .addComponent(buttonPageRiwayat)
                    .addComponent(buttonPageKurir)
                    .addComponent(buttonPagePelanggan)
                    .addComponent(buttonPageSampah))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPageSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPageSampahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPageSampahActionPerformed

    private void buttonPagePermintaanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonPagePermintaanActionPerformed
        // TODO add your handling code here:
        PermintaanCRUD permintaanCRUD = new PermintaanCRUD(new PermintaanDao());
        permintaanCRUD.setVisible(true);
    }// GEN-LAST:event_buttonPagePermintaanActionPerformed

    private void buttonPageLacakActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonPageLacakActionPerformed
        // TODO add your handling code here:
        LacakCRUD lacakCRUD = new LacakCRUD(new LacakDao());
        lacakCRUD.setVisible(true);
    }// GEN-LAST:event_buttonPageLacakActionPerformed

    private void buttonPageKurirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonPageKurirActionPerformed
        // TODO add your handling code here:
        KurirCRUD kurirCRUD = new KurirCRUD(new KurirDao());
        kurirCRUD.setVisible(true);
    }// GEN-LAST:event_buttonPageKurirActionPerformed

    private void buttonPagePenjemputanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonPagePenjemputanActionPerformed
        // TODO add your handling code here:
        PenjemputanCRUD penjemputanCRUD = new PenjemputanCRUD(new PenjemputanDao());
        penjemputanCRUD.setVisible(true);
    }// GEN-LAST:event_buttonPagePenjemputanActionPerformed

    private void buttonPagePelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonPagePelangganActionPerformed
        // TODO add your handling code here:
        PelangganCRUD pelangganCRUD = new PelangganCRUD(new PelangganDao());
        pelangganCRUD.setVisible(true);
    }// GEN-LAST:event_buttonPagePelangganActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPageKurir;
    private javax.swing.JButton buttonPageLacak;
    private javax.swing.JButton buttonPagePelanggan;
    private javax.swing.JButton buttonPagePenjemputan;
    private javax.swing.JButton buttonPagePermintaan;
    private javax.swing.JButton buttonPageRiwayat;
    private javax.swing.JButton buttonPageSampah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelCRUD;
    // End of variables declaration//GEN-END:variables
}
