/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.kurir;

import id.ac.unpas.techIn.kurir.*;
import id.ac.unpas.techIn.dao.KurirDao;
import id.ac.unpas.techIn.pelanggan.Pelanggan;
import id.ac.unpas.techIn.penjemputan.Penjemputan;
import id.ac.unpas.techIn.kurir.KurirModelTable;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ghifarullah19
 */
public class KurirCRUD
        extends javax.swing.JFrame {
    
    private List<Kurir> kurirList;
    private Kurir kurirUbah;
    private KurirDao kurirDao;
    private KurirModelTable kurirModelTable;

    /**
     * Creates new form KurirCRUD
     */
    public KurirCRUD(KurirDao kurirDao) {
        this.kurirDao = kurirDao;
        this.kurirList = this.kurirDao.findAll();
        this.kurirModelTable = new KurirModelTable(kurirList);
        
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        frameCRUDKurir = new javax.swing.JPanel();
        panelCRUDKurir = new javax.swing.JPanel();
        titleCRUDPermintaan = new javax.swing.JLabel();
        buttonKirim = new javax.swing.JButton();
        labelNamaKurir = new javax.swing.JLabel();
        textfieldNamaKurir = new javax.swing.JTextField();
        labeNoKendaraanKurir = new javax.swing.JLabel();
        textfieldNoKendaraan = new javax.swing.JTextField();
        scrollableTable = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKurir = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameCRUDKurir.setBackground(new java.awt.Color(102, 153, 255));

        panelCRUDKurir.setBackground(new java.awt.Color(255, 255, 255));

        titleCRUDPermintaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCRUDPermintaan.setText("Form Kurir");

        buttonKirim.setText("Kirim");
        buttonKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKirimActionPerformed(evt);
            }
        });

        labelNamaKurir.setText("Nama Kurir");

        textfieldNamaKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaKurirActionPerformed(evt);
            }
        });

        labeNoKendaraanKurir.setText("No Kendaraan");

        textfieldNoKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNoKendaraanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDKurirLayout = new javax.swing.GroupLayout(panelCRUDKurir);
        panelCRUDKurir.setLayout(panelCRUDKurirLayout);
        panelCRUDKurirLayout.setHorizontalGroup(
            panelCRUDKurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDKurirLayout.createSequentialGroup()
                .addGroup(panelCRUDKurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCRUDKurirLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCRUDKurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonKirim)
                            .addComponent(labelNamaKurir)
                            .addComponent(textfieldNamaKurir, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labeNoKendaraanKurir)
                            .addComponent(textfieldNoKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCRUDKurirLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(titleCRUDPermintaan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCRUDKurirLayout.setVerticalGroup(
            panelCRUDKurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDKurirLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleCRUDPermintaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNamaKurir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldNamaKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeNoKendaraanKurir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldNoKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonKirim)
                .addGap(74, 74, 74))
        );

        tableKurir.setModel(kurirModelTable);
        jScrollPane1.setViewportView(tableKurir);

        scrollableTable.setViewportView(jScrollPane1);

        javax.swing.GroupLayout frameCRUDKurirLayout = new javax.swing.GroupLayout(frameCRUDKurir);
        frameCRUDKurir.setLayout(frameCRUDKurirLayout);
        frameCRUDKurirLayout.setHorizontalGroup(
            frameCRUDKurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCRUDKurirLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(frameCRUDKurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCRUDKurir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollableTable, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        frameCRUDKurirLayout.setVerticalGroup(
            frameCRUDKurirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCRUDKurirLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelCRUDKurir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollableTable, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameCRUDKurir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameCRUDKurir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKirimActionPerformed
        // TODO add your handling code here:
        
        String namaKurir = this.textfieldNamaKurir.getText();
        String noKendaraan = this.textfieldNoKendaraan.getText();

        Kurir kurir = new Kurir();
        Penjemputan penjemputan = new Penjemputan();
        
        kurir.setNama(namaKurir);
        kurir.setNoKendaraan(noKendaraan);
        
        int confirmation = JOptionPane.showConfirmDialog(KurirCRUD.this,"Apakah yakin ingin menyimpan data?", 
                       "Peringatan!", JOptionPane.YES_NO_OPTION);
        
        if (confirmation == JOptionPane.YES_OPTION) { //Jika Confirmation Option bernilai "Yes"
            this.kurirDao.insert(kurir);
            this.addData(kurir);
               } else { //Jika tidak,
                   JOptionPane.showMessageDialog(KurirCRUD.this, "Data tidak disimpan"); 
               }

        
    }//GEN-LAST:event_buttonKirimActionPerformed

    private void textfieldNamaKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaKurirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaKurirActionPerformed

    private void textfieldNoKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNoKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNoKendaraanActionPerformed

    // Method untuk menambahkan kurir ke tableModel
    public void addData(Kurir kurir) {
        kurirModelTable.add(kurir);
        textfieldNamaKurir.setText("");
        textfieldNoKendaraan.setText("");
    }
    
    // Method untuk mengubah kurir ke tableModel
    public void update(Kurir kurir) {
        kurirModelTable.update(kurir);
        textfieldNamaKurir.setText("");
        textfieldNoKendaraan.setText("");
    }
    
    // Method untuk menghapus kurir ke tableModel
    public void delete(Kurir kurir) {
        // Tambahkan kurir ke tableModel
        kurirModelTable.delete(kurir);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton buttonKirim;
    private javax.swing.JPanel frameCRUDKurir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeNoKendaraanKurir;
    private javax.swing.JLabel labelNamaKurir;
    private javax.swing.JPanel panelCRUDKurir;
    private javax.swing.JScrollPane scrollableTable;
    private javax.swing.JTable tableKurir;
    private javax.swing.JTextField textfieldNamaKurir;
    private javax.swing.JTextField textfieldNoKendaraan;
    private javax.swing.JLabel titleCRUDPermintaan;
    // End of variables declaration//GEN-END:variables
}
