/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.lacak;

import id.ac.unpas.techIn.lacak.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author ghifarullah19
 */
public class LacakCard
        extends javax.swing.JFrame {

    /**
     * Creates new form PermintaanFrame
     */
    public LacakCard() {
        initComponents();
        
    }
    
    public JPanel getFrame() {
        return this.lacakPanel;
    }
    
    public void setPanelData(Lacak kurir) {
        namaKurir.setText(kurir.getNamaKurir());
        alamatPenjemputan.setText(kurir.getAlamatPenjemputan());
        
        if (kurir.getStatus()) {
            status.setText("Sudah dijemput");
        } else {
            status.setText("Sedang dalam penjemputan");
        }
        
        iconMobil.setText("");
        iconMobil.setIcon(imageIcon("C:\\Users\\ghifarullah19\\Documents\\NetBeansProjects\\tech-in\\src\\main\\java\\id\\ac\\unpas\\techIn\\img\\mobil-free.png",
                70,
                70));
    }
    
    public ImageIcon imageIcon(String imageURL, int height, int width) {
        ImageIcon icon = new ImageIcon(imageURL);
        Image image = icon.getImage();
        Image newImage = image.getScaledInstance(width,
                        height,
                        Image.SCALE_SMOOTH);
        icon = new ImageIcon(newImage);
        return icon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jPanel2 = new javax.swing.JPanel();
        jOptionPane1 = new javax.swing.JOptionPane();
        lacakPanel = new javax.swing.JPanel();
        buttonLacak = new javax.swing.JButton();
        namaKurir = new javax.swing.JLabel();
        alamatPenjemputan = new javax.swing.JLabel();
        iconMobil = new javax.swing.JLabel();
        status = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lacakPanel.setBackground(new java.awt.Color(255, 255, 255));
        lacakPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lacakPanel.setForeground(new java.awt.Color(0, 102, 204));
        lacakPanel.setMaximumSize(new java.awt.Dimension(556, 131));

        buttonLacak.setBackground(new java.awt.Color(153, 153, 153));
        buttonLacak.setForeground(new java.awt.Color(51, 51, 51));
        buttonLacak.setText("Lacak");
        buttonLacak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLacakActionPerformed(evt);
            }
        });

        namaKurir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namaKurir.setForeground(new java.awt.Color(0, 102, 204));
        namaKurir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaKurir.setText("namaKurir");

        alamatPenjemputan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alamatPenjemputan.setForeground(new java.awt.Color(0, 102, 204));
        alamatPenjemputan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alamatPenjemputan.setText("alamatPenjemputan");

        iconMobil.setText("iconMaps");

        status.setBackground(new java.awt.Color(51, 102, 255));
        status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        status.setForeground(new java.awt.Color(51, 102, 255));
        status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        status.setText("status");

        javax.swing.GroupLayout lacakPanelLayout = new javax.swing.GroupLayout(lacakPanel);
        lacakPanel.setLayout(lacakPanelLayout);
        lacakPanelLayout.setHorizontalGroup(
            lacakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lacakPanelLayout.createSequentialGroup()
                .addGroup(lacakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lacakPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alamatPenjemputan, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(buttonLacak))
                    .addGroup(lacakPanelLayout.createSequentialGroup()
                        .addGroup(lacakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lacakPanelLayout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(namaKurir, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lacakPanelLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lacakPanelLayout.setVerticalGroup(
            lacakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lacakPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaKurir)
                .addGroup(lacakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconMobil, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(lacakPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lacakPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatPenjemputan, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lacakPanelLayout.createSequentialGroup()
                                .addComponent(buttonLacak)
                                .addGap(11, 11, 11)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lacakPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lacakPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLacakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLacakActionPerformed
        // TODO add your handling code here:
        Lacak lacak = new Lacak();
        lacak.setAlamatPenjemputan(alamatPenjemputan.getText());
        LacakDetailFrame lacakDetailFrame = new LacakDetailFrame(lacak);
        lacakDetailFrame.setVisible(true);
    }//GEN-LAST:event_buttonLacakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LacakCard.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LacakCard.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LacakCard.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LacakCard.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LacakCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatPenjemputan;
    private javax.swing.JButton buttonLacak;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel iconMobil;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel lacakPanel;
    private javax.swing.JLabel namaKurir;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
