/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.lacak;

import id.ac.unpas.techIn.lacak.*;
import java.util.List;
import id.ac.unpas.techIn.dao.LacakDao;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author ghifarullah19
 */
public class LacakFrame
        extends javax.swing.JFrame {
    
    // jenisMemberList adalah variabel yang digunakan untuk menyimpan data jenis member
    private List<Lacak> lacakList;
    
    // jenisMemberDao adalah variabel yang digunakan untuk menyimpan data jenis member yang didapat dari database
    private LacakDao lacakDao;

    /**
     * Creates new form LacakFrame2
     */
    public LacakFrame(LacakDao lacakDao) {
        // this.jenisMemberDao diberikan nilai dari parameter jenisMemberDao
        this.lacakDao = lacakDao;
        // this.jenisMemberList diberikan nilai dari data jenis member yang didapat dari database
        this.lacakList = this.lacakDao.findAll();
        
        initComponents();
        
//        showLacakPane.setLayout(new BoxLayout(showLacakPane, BoxLayout.PAGE_AXIS));
        showLacakPane.setLayout(new GridLayout(lacakList.size(), 1, 0, 10));
        
        for (int i = 0; i < lacakList.size(); i++) {
            JPanel panel = new JPanel();
            LacakCard lacak = new LacakCard();
            lacak.setPanelData(lacakList.get(i));
            panel.setBackground(new Color(0,0,0,0));
            panel.add(lacak.getFrame());
            showLacakPane.add(panel);
        }
        showLacakScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLacak = new javax.swing.JPanel();
        panelTitlePermintaan = new javax.swing.JPanel();
        labelTitlePermintaan = new javax.swing.JLabel();
        showLacakScrollPane = new javax.swing.JScrollPane();
        showLacakPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelLacak.setBackground(new java.awt.Color(155, 190, 200));

        panelTitlePermintaan.setBackground(new java.awt.Color(22, 72, 99));

        labelTitlePermintaan.setFont(new java.awt.Font("Kaushan Script", 0, 12)); // NOI18N
        labelTitlePermintaan.setForeground(new java.awt.Color(255, 255, 255));
        labelTitlePermintaan.setText("Lacak");

        javax.swing.GroupLayout panelTitlePermintaanLayout = new javax.swing.GroupLayout(panelTitlePermintaan);
        panelTitlePermintaan.setLayout(panelTitlePermintaanLayout);
        panelTitlePermintaanLayout.setHorizontalGroup(
            panelTitlePermintaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitlePermintaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitlePermintaan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitlePermintaanLayout.setVerticalGroup(
            panelTitlePermintaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitlePermintaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitlePermintaan)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        showLacakPane.setBackground(new java.awt.Color(155, 190, 200));

        javax.swing.GroupLayout showLacakPaneLayout = new javax.swing.GroupLayout(showLacakPane);
        showLacakPane.setLayout(showLacakPaneLayout);
        showLacakPaneLayout.setHorizontalGroup(
            showLacakPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        showLacakPaneLayout.setVerticalGroup(
            showLacakPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        showLacakScrollPane.setViewportView(showLacakPane);

        javax.swing.GroupLayout panelLacakLayout = new javax.swing.GroupLayout(panelLacak);
        panelLacak.setLayout(panelLacakLayout);
        panelLacakLayout.setHorizontalGroup(
            panelLacakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitlePermintaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(showLacakScrollPane)
        );
        panelLacakLayout.setVerticalGroup(
            panelLacakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLacakLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(panelTitlePermintaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showLacakScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLacak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLacak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelTitlePermintaan;
    private javax.swing.JPanel panelLacak;
    private javax.swing.JPanel panelTitlePermintaan;
    private javax.swing.JPanel showLacakPane;
    private javax.swing.JScrollPane showLacakScrollPane;
    // End of variables declaration//GEN-END:variables
}
