/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.sampah;

import id.ac.unpas.techIn.dao.KurirDao;
import id.ac.unpas.techIn.dao.PelangganDao;
import id.ac.unpas.techIn.dao.PermintaanDao;
import id.ac.unpas.techIn.dao.RiwayatDao;
import id.ac.unpas.techIn.sampah.*;
import id.ac.unpas.techIn.dao.SampahDao;
import id.ac.unpas.techIn.penjemputan.Penjemputan;
import id.ac.unpas.techIn.riwayat.Riwayat;
import id.ac.unpas.techIn.sampah.SampahModelTable;
import java.util.List;

/**
 *
 * @author ghifarullah19
 */
public class SampahCRUD
        extends javax.swing.JFrame {
    
    private List<Sampah> sampahList;
    private Sampah sampahUbah;
    private SampahDao sampahDao;
    private SampahModelTable sampahModelTable;

    /**
     * Creates new form SampahCRUD
     */
    public SampahCRUD(SampahDao sampahDao) {
        this.sampahDao = sampahDao;
        this.sampahList = this.sampahDao.findAll();
        this.sampahModelTable = new SampahModelTable(sampahList);
        
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        frameCRUDSampah = new javax.swing.JPanel();
        panelCRUDSampah = new javax.swing.JPanel();
        titleCRUDSampah = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKirim = new javax.swing.JButton();
        buttonSimpanUbah = new javax.swing.JButton();
        labelNamaPelanggan = new javax.swing.JLabel();
        textfieldNamaPelanggan = new javax.swing.JTextField();
        labeNoKendaraanKurir = new javax.swing.JLabel();
        textfieldNoKendaraan = new javax.swing.JTextField();
        textfieldNamaKurir = new javax.swing.JTextField();
        labelNamaKurir = new javax.swing.JLabel();
        textfieldPoin = new javax.swing.JTextField();
        labelNamaPelanggan1 = new javax.swing.JLabel();
        labelJenisSampah = new javax.swing.JLabel();
        textfieldJenisSampah = new javax.swing.JTextField();
        labelBeratSampah = new javax.swing.JLabel();
        textfieldBeratSampah = new javax.swing.JTextField();
        labelJumlahSampah = new javax.swing.JLabel();
        textfieldJumlahSampah = new javax.swing.JTextField();
        labelAlamatPenjemputan = new javax.swing.JLabel();
        textfieldAlamatPenjemputan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textfieldHargaSampah = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        scrollableTable = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSampah = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameCRUDSampah.setBackground(new java.awt.Color(102, 153, 255));

        panelCRUDSampah.setBackground(new java.awt.Color(255, 255, 255));

        titleCRUDSampah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCRUDSampah.setText("Form Sampah");

        buttonKembali.setText("Kembali");

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonKirim.setText("Kirim");
        buttonKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKirimActionPerformed(evt);
            }
        });

        buttonSimpanUbah.setText("Simpan Ubah");
        buttonSimpanUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanUbahActionPerformed(evt);
            }
        });

        labelNamaPelanggan.setText("Nama Pelanggan");

        textfieldNamaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaPelangganActionPerformed(evt);
            }
        });

        labeNoKendaraanKurir.setText("No Kendaraan");

        textfieldNoKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNoKendaraanActionPerformed(evt);
            }
        });

        textfieldNamaKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaKurirActionPerformed(evt);
            }
        });

        labelNamaKurir.setText("Nama Kurir");

        textfieldPoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldPoinActionPerformed(evt);
            }
        });

        labelNamaPelanggan1.setText("Poin");

        labelJenisSampah.setText("Jenis Sampah");

        textfieldJenisSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldJenisSampahActionPerformed(evt);
            }
        });

        labelBeratSampah.setText("Berat Sampah");

        textfieldBeratSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldBeratSampahActionPerformed(evt);
            }
        });

        labelJumlahSampah.setText("Jumlah Sampah");

        textfieldJumlahSampah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldJumlahSampahActionPerformed(evt);
            }
        });

        labelAlamatPenjemputan.setText("Alamat Penjemputan");

        jLabel1.setText("Harga Sampah");

        javax.swing.GroupLayout panelCRUDSampahLayout = new javax.swing.GroupLayout(panelCRUDSampah);
        panelCRUDSampah.setLayout(panelCRUDSampahLayout);
        panelCRUDSampahLayout.setHorizontalGroup(
            panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDSampahLayout.createSequentialGroup()
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCRUDSampahLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(titleCRUDSampah))
                    .addGroup(panelCRUDSampahLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panelCRUDSampahLayout.createSequentialGroup()
                                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textfieldHargaSampah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldNamaPelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNamaPelanggan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelJenisSampah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldJenisSampah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelJumlahSampah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldJumlahSampah, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAlamatPenjemputan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldAlamatPenjemputan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBeratSampah)
                                    .addComponent(labelNamaKurir)
                                    .addComponent(textfieldNamaKurir, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labeNoKendaraanKurir)
                                    .addComponent(textfieldNoKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfieldBeratSampah, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textfieldPoin, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNamaPelanggan1)))
                            .addGroup(panelCRUDSampahLayout.createSequentialGroup()
                                .addComponent(buttonKembali)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSimpanUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonKirim)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        panelCRUDSampahLayout.setVerticalGroup(
            panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDSampahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleCRUDSampah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNamaPelanggan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelNamaKurir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textfieldNamaKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamatPenjemputan)
                    .addComponent(labeNoKendaraanKurir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldNoKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldAlamatPenjemputan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJenisSampah)
                    .addComponent(labelBeratSampah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldJenisSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldBeratSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCRUDSampahLayout.createSequentialGroup()
                        .addComponent(labelJumlahSampah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldJumlahSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCRUDSampahLayout.createSequentialGroup()
                        .addComponent(labelNamaPelanggan1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldPoin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldHargaSampah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(panelCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKembali)
                    .addComponent(buttonUbah)
                    .addComponent(buttonSimpanUbah)
                    .addComponent(buttonHapus)
                    .addComponent(buttonKirim))
                .addContainerGap())
        );

        tableSampah.setModel(sampahModelTable);
        jScrollPane1.setViewportView(tableSampah);

        scrollableTable.setViewportView(jScrollPane1);

        javax.swing.GroupLayout frameCRUDSampahLayout = new javax.swing.GroupLayout(frameCRUDSampah);
        frameCRUDSampah.setLayout(frameCRUDSampahLayout);
        frameCRUDSampahLayout.setHorizontalGroup(
            frameCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCRUDSampahLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(frameCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCRUDSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollableTable, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        frameCRUDSampahLayout.setVerticalGroup(
            frameCRUDSampahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCRUDSampahLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelCRUDSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollableTable, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameCRUDSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameCRUDSampah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKirimActionPerformed
        // TODO add your handling code here:
        KurirDao kurirDao = new KurirDao();
        PelangganDao pelangganDao = new PelangganDao();
        
        String namaPelanggan = this.textfieldNamaPelanggan.getText();
        String noKendaraan = this.textfieldNoKendaraan.getText();
        String namaKurir = this.textfieldNamaKurir.getText();
        String alamatPenjemputan = this.textfieldAlamatPenjemputan.getText();
        String jenisSampah = this.textfieldJenisSampah.getText();
        float beratSampah = Float.valueOf(this.textfieldBeratSampah.getText());
        float hargaSampah = Float.valueOf(this.textfieldHargaSampah.getText());
        int jumlahSampah = Integer.valueOf(textfieldJumlahSampah.getText());
        int poinSampah = Integer.valueOf(textfieldPoin.getText());

        Sampah sampah = new Sampah();
        
        sampah.setNamaPelanggan(namaPelanggan);
        sampah.setAlamatPenjemputan(alamatPenjemputan);
        sampah.setNoKendaraan(noKendaraan);
        sampah.setNamaKurir(namaKurir);
        sampah.setJenisSampah(jenisSampah);
        sampah.setBeratSampah(beratSampah);
        sampah.setHargaSampah(hargaSampah);
        sampah.setJumlahSampah(jumlahSampah);
        sampah.setPoin(poinSampah);
        sampah.setIdKurir(kurirDao.select("namaKurir",namaKurir).getId());
        sampah.setIdPelanggan(pelangganDao.select("namaPelanggan",namaPelanggan).getId());
        
        this.sampahDao.insert(sampah);
        this.addData(sampah);
    }//GEN-LAST:event_buttonKirimActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        int row = tableSampah.getSelectedRow();
        int column = tableSampah.getSelectedColumn();

        if (row == -1 || column == -1) {
            return;
        }

        String dataUbah = (String) tableSampah.getModel().getValueAt(row, column);

        int id = -1;
        String col = "";

        switch (column) {
            case 0:
                col = "jumlahSampah";
                break;
            case 1:
                col = "jenisSampah";
                break;
            case 2:
                col = "beratSampah";
                break;
            case 3:
                col = "poin";
                break;
            default:
                System.out.println("Kolom tidak ditemukan");
                break;
        }
        id = this.sampahDao.select(col, dataUbah).getId();
       System.out.println(col + " " + dataUbah);
        this.textfieldJumlahSampah.setText(String.valueOf(this.sampahDao.select(col, dataUbah).getJumlahSampah()));
        this.textfieldJenisSampah.setText(String.valueOf(this.sampahDao.select(col, dataUbah).getJenisSampah()));
        this.textfieldBeratSampah.setText(String.valueOf(this.sampahDao.select(col, dataUbah).getBeratSampah()));
        this.textfieldPoin.setText(String.valueOf(this.sampahDao.select(col, dataUbah).getPoin()));
        
        sampahUbah = new Sampah();
        sampahUbah.setId(id);
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonSimpanUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanUbahActionPerformed
        // TODO add your handling code here:
        RiwayatDao riwayatDao = new RiwayatDao();
        
        String jenisSampah = this.textfieldJenisSampah.getText();
        int jumlahSampah = Integer.valueOf(this.textfieldJumlahSampah.getText());
        float beratSampah = Float.valueOf(this.textfieldBeratSampah.getText());
        int poin = Integer.valueOf(this.textfieldPoin.getText());

        Sampah sampah = new Sampah();
        sampah.setJenisSampah(jenisSampah);
        sampah.setJumlahSampah(jumlahSampah);
        sampah.setBeratSampah(beratSampah);
        sampah.setPoin(poin);
        
        Riwayat riwayat = new Riwayat();
        riwayat.setIdSampah(sampahDao.select("jenisSampah",jenisSampah).getId());
        riwayat.setJumlahSampah(jumlahSampah);
        riwayat.setBeratSampah(beratSampah);
        riwayat.setPoinSampah(poin);

        this.sampahDao.update(sampah);
        riwayatDao.update(riwayat);
        this.update(sampah);
    }//GEN-LAST:event_buttonSimpanUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int row = this.tableSampah.getSelectedRow();
        int column = this.tableSampah.getSelectedColumn();

        if (row == -1 || column == -1) {
          return;
        } else {
            String newValue = (String) this.tableSampah.getModel().getValueAt(row, column);
     
            Sampah id = new Sampah();

            String col = "";

            switch (column) {
                case 0:
                    col = "jumlahSampah";
                    break;
                case 1:
                    col = "jenisSampah";
                    break;
                case 2:
                    col = "beratSampah";
                    break;
                case 3:
                    col = "poin";
                    break;
                default:
                    System.out.println("Kolom tidak ditemukan");
                    break;
            }
            id = this.sampahDao.select(col, newValue);

            this.delete(id);
            this.sampahDao.delete(id);
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void textfieldNamaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaPelangganActionPerformed

    private void textfieldNoKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNoKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNoKendaraanActionPerformed

    private void textfieldNamaKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNamaKurirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNamaKurirActionPerformed

    private void textfieldPoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldPoinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldPoinActionPerformed

    private void textfieldJenisSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldJenisSampahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldJenisSampahActionPerformed

    private void textfieldBeratSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldBeratSampahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldBeratSampahActionPerformed

    private void textfieldJumlahSampahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldJumlahSampahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldJumlahSampahActionPerformed

    // Method untuk menambahkan sampah ke tableModel
    public void addData(Sampah sampah) {
        sampahModelTable.add(sampah);
        textfieldNamaPelanggan.setText("");
        textfieldNoKendaraan.setText("");
    }
    
    // Method untuk mengubah sampah ke tableModel
    public void update(Sampah sampah) {
        sampahModelTable.update(sampah);
        textfieldNamaPelanggan.setText("");
        textfieldNoKendaraan.setText("");
    }
    
    // Method untuk menghapus sampah ke tableModel
    public void delete(Sampah sampah) {
        // Tambahkan sampah ke tableModel
        sampahModelTable.delete(sampah);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonKirim;
    private javax.swing.JButton buttonSimpanUbah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JPanel frameCRUDSampah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labeNoKendaraanKurir;
    private javax.swing.JLabel labelAlamatPenjemputan;
    private javax.swing.JLabel labelBeratSampah;
    private javax.swing.JLabel labelJenisSampah;
    private javax.swing.JLabel labelJumlahSampah;
    private javax.swing.JLabel labelNamaKurir;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JLabel labelNamaPelanggan1;
    private javax.swing.JPanel panelCRUDSampah;
    private javax.swing.JScrollPane scrollableTable;
    private javax.swing.JTable tableSampah;
    private javax.swing.JTextField textfieldAlamatPenjemputan;
    private javax.swing.JTextField textfieldBeratSampah;
    private javax.swing.JTextField textfieldHargaSampah;
    private javax.swing.JTextField textfieldJenisSampah;
    private javax.swing.JTextField textfieldJumlahSampah;
    private javax.swing.JTextField textfieldNamaKurir;
    private javax.swing.JTextField textfieldNamaPelanggan;
    private javax.swing.JTextField textfieldNoKendaraan;
    private javax.swing.JTextField textfieldPoin;
    private javax.swing.JLabel titleCRUDSampah;
    // End of variables declaration//GEN-END:variables
}
