/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.unpas.techIn.penjemputan;

import id.ac.unpas.techIn.dao.KurirDao;
import id.ac.unpas.techIn.permintaan.*;
import id.ac.unpas.techIn.dao.PermintaanDao;
import id.ac.unpas.techIn.dao.PenjemputanDao;
import id.ac.unpas.techIn.kurir.Kurir;
import id.ac.unpas.techIn.pelanggan.Pelanggan;
import id.ac.unpas.techIn.penjemputan.Penjemputan;
import id.ac.unpas.techIn.permintaan.Permintaan;
import id.ac.unpas.techIn.permintaan.PermintaanModelTable;
import id.ac.unpas.techIn.penjemputan.PenjemputanModelTable;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ghifarullah19
 */
public class PenjemputanCRUD
        extends javax.swing.JFrame {

    private List<Penjemputan> penjemputanList;
    private Penjemputan penjemputanUbah;
    private PenjemputanDao penjemputanDao;
    private PenjemputanModelTable penjemputanModelTable;

    /**
     * Creates new form PenjemputanCRUD
     */
    public PenjemputanCRUD(PenjemputanDao penjemputanDao) {
        this.penjemputanDao = penjemputanDao;
        this.penjemputanList = this.penjemputanDao.findAll();
        this.penjemputanModelTable = new PenjemputanModelTable(penjemputanList);

        initComponents();

        buttonGroup1.add(radioTrue);
        buttonGroup1.add(radioFalse);

        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        frameCRUDPenjemputan = new javax.swing.JPanel();
        panelCRUDPenjemputan = new javax.swing.JPanel();
        labelNamaPelanggan = new javax.swing.JLabel();
        textfieldNamaPelanggan = new javax.swing.JTextField();
        labelAlamatPelanggan = new javax.swing.JLabel();
        textfieldAlamatPelanggan = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();
        radioTrue = new javax.swing.JRadioButton();
        radioFalse = new javax.swing.JRadioButton();
        titleCRUDPermintaan = new javax.swing.JLabel();
        buttonUbah = new javax.swing.JButton();
        buttonSimpanUbah = new javax.swing.JButton();
        labelNamaKurir = new javax.swing.JLabel();
        textfieldNamaKurir = new javax.swing.JTextField();
        labelAlamatTujuan = new javax.swing.JLabel();
        textfieldAlamatTujuan = new javax.swing.JTextField();
        buttonRefresh = new javax.swing.JButton();
        scrollableTable = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePenjemputan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        frameCRUDPenjemputan.setBackground(new java.awt.Color(102, 153, 255));

        panelCRUDPenjemputan.setBackground(new java.awt.Color(255, 255, 255));

        labelNamaPelanggan.setText("Nama Pelanggan");

        textfieldNamaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaPelangganActionPerformed(evt);
            }
        });

        labelAlamatPelanggan.setText("Almat Penjemputan");

        textfieldAlamatPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldAlamatPelangganActionPerformed(evt);
            }
        });

        labelStatus.setText("Status");

        radioTrue.setText("Menjemput");

        radioFalse.setText("Tidak Menjemput");

        titleCRUDPermintaan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCRUDPermintaan.setText("Form Penjemputan");

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonSimpanUbah.setText("Simpan Ubah");
        buttonSimpanUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanUbahActionPerformed(evt);
            }
        });

        labelNamaKurir.setText("Nama Kurir");

        textfieldNamaKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNamaKurirActionPerformed(evt);
            }
        });

        labelAlamatTujuan.setText("Alamat Tujuan");

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCRUDPenjemputanLayout = new javax.swing.GroupLayout(panelCRUDPenjemputan);
        panelCRUDPenjemputan.setLayout(panelCRUDPenjemputanLayout);
        panelCRUDPenjemputanLayout.setHorizontalGroup(
            panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDPenjemputanLayout.createSequentialGroup()
                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCRUDPenjemputanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCRUDPenjemputanLayout.createSequentialGroup()
                                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNamaPelanggan)
                                    .addComponent(labelAlamatPelanggan)
                                    .addComponent(textfieldAlamatPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(textfieldNamaPelanggan))
                                .addGap(59, 59, 59)
                                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNamaKurir)
                                    .addComponent(textfieldNamaKurir)
                                    .addComponent(labelAlamatTujuan)
                                    .addComponent(textfieldAlamatTujuan, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)))
                            .addComponent(labelStatus)
                            .addGroup(panelCRUDPenjemputanLayout.createSequentialGroup()
                                .addComponent(radioTrue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioFalse))))
                    .addGroup(panelCRUDPenjemputanLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(titleCRUDPermintaan))
                    .addGroup(panelCRUDPenjemputanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(buttonUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonSimpanUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRefresh)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCRUDPenjemputanLayout.setVerticalGroup(
            panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCRUDPenjemputanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleCRUDPermintaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaPelanggan)
                    .addComponent(labelNamaKurir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldNamaKurir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlamatPelanggan)
                    .addComponent(labelAlamatTujuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldAlamatPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldAlamatTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTrue)
                    .addComponent(radioFalse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUbah)
                    .addComponent(buttonSimpanUbah)
                    .addComponent(buttonRefresh))
                .addGap(52, 52, 52))
        );

        tablePenjemputan.setModel(penjemputanModelTable);
        jScrollPane1.setViewportView(tablePenjemputan);

        scrollableTable.setViewportView(jScrollPane1);

        javax.swing.GroupLayout frameCRUDPenjemputanLayout = new javax.swing.GroupLayout(frameCRUDPenjemputan);
        frameCRUDPenjemputan.setLayout(frameCRUDPenjemputanLayout);
        frameCRUDPenjemputanLayout.setHorizontalGroup(
            frameCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCRUDPenjemputanLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(frameCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCRUDPenjemputan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollableTable, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        frameCRUDPenjemputanLayout.setVerticalGroup(
            frameCRUDPenjemputanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCRUDPenjemputanLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panelCRUDPenjemputan, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollableTable, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameCRUDPenjemputan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameCRUDPenjemputan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonRefreshActionPerformed
        // TODO add your handling code here:
        KurirDao kurirDao = new KurirDao();
        List<Kurir> kurirList = kurirDao.findAll();

        for (int i = 0; i < kurirList.size(); i++) {
            Kurir kurir = new Kurir();
            kurir = kurirList.get(i);

            if (penjemputanDao.select("namaKurir", kurir.getNama()).getNama() != null) {
                continue;
            } else {
                Penjemputan penjemputan = new Penjemputan();
                penjemputan.setNama(kurir.getNama());
                penjemputan.setAlamat("");
                penjemputan.setAlamatTujuan("");
                penjemputan.setStatus(true);
                penjemputan.setIdKurir(kurir.getId());
                penjemputan.setIdPermintaan(0);
                this.addData(penjemputan);
                penjemputanDao.insert(kurir);
            }
        }
    }// GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        int row = tablePenjemputan.getSelectedRow();
        int column = tablePenjemputan.getSelectedColumn();

        if (row == -1 || column == -1) {
            return;
        }

        String dataUbah = (String) tablePenjemputan.getModel().getValueAt(row, column);

        int id = -1;
        String col = "";

        switch (column) {
            case 0:
                col = "namaKurir";
                break;
            case 1:
                col = "alamatPenjemputan";
                break;
            case 2:
                col = "status";
                break;
            default:
                System.out.println("Kolom tidak ditemukan");
                break;
        }
        PermintaanDao permintaanDao = new PermintaanDao();

        id = this.penjemputanDao.select(col, dataUbah).getId();
        int idPermintaan = this.penjemputanDao.select(col, dataUbah).getIdPermintaan();

        this.textfieldNamaKurir.setText(this.penjemputanDao.select(col, dataUbah).getNama());
        this.textfieldNamaPelanggan.setText(permintaanDao.select("id", String.valueOf(idPermintaan)).getNama());
        this.textfieldAlamatPelanggan.setText(this.penjemputanDao.select(col, dataUbah).getAlamat());
        this.textfieldAlamatTujuan.setText(this.penjemputanDao.select(col, dataUbah).getAlamatTujuan());

        if (this.penjemputanDao.select(col, dataUbah).getStatus() == true) {
            this.radioFalse.setSelected(true);
        } else {
            this.radioTrue.setSelected(true);
        }

        penjemputanUbah = new Penjemputan();
        penjemputanUbah.setId(id);
    }// GEN-LAST:event_buttonUbahActionPerformed

    private void buttonSimpanUbahActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSimpanUbahActionPerformed
        // TODO add your handling code here:
        boolean status = false;

        if (radioTrue.isSelected()) {
            status = false;
        }

        if (radioFalse.isSelected()) {
            status = true;
        }

        String nama = this.textfieldNamaKurir.getText();
        String alamat = this.textfieldAlamatTujuan.getText();

        Permintaan penjemputan = new Permintaan();
        penjemputan.setId(penjemputanUbah.getId());
        penjemputan.setNama(nama);
        penjemputan.setAlamat(alamat);
        penjemputan.setStatus(status);

        PermintaanDao permintaanDao = new PermintaanDao();

        int confirmation = JOptionPane.showConfirmDialog(PenjemputanCRUD.this,"Apakah yakin ingin mengubah data?", 
                       "Peringatan!", JOptionPane.YES_NO_OPTION);
        
        if (confirmation == JOptionPane.YES_OPTION) { //Jika Confirmation Option bernilai "Yes"
            permintaanDao.updateBasedPenjemputan(penjemputan);
            this.textfieldNamaKurir.setText("");
            this.textfieldNamaPelanggan.setText("");
            this.textfieldAlamatTujuan.setText("");
            this.textfieldAlamatPelanggan.setText("");
        } else { //Jika tidak,
            JOptionPane.showMessageDialog(PenjemputanCRUD.this, "Data tidak diubah"); 
        }
    }// GEN-LAST:event_buttonSimpanUbahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int row = this.tablePenjemputan.getSelectedRow();
        int column = this.tablePenjemputan.getSelectedColumn();

        if (row == -1 || column == -1) {
            return;
        } else {
            String newValue = (String) this.tablePenjemputan.getModel().getValueAt(row, column);

            Penjemputan id = new Penjemputan();

            String col = "";

            switch (column) {
                case 0:
                    col = "namaKurir";
                    break;
                case 1:
                    col = "alamatPenjemputan";
                    break;
                case 2:
                    col = "status";
                    break;
                default:
                    System.out.println("Kolom tidak ditemukan");
                    break;
            }
            id = this.penjemputanDao.select(col, newValue);

            int confirmation = JOptionPane.showConfirmDialog(PenjemputanCRUD.this,"Apakah yakin ingin menghapus data?", 
                       "Peringatan!", JOptionPane.YES_NO_OPTION);
        
            if (confirmation == JOptionPane.YES_OPTION) { //Jika Confirmation Option bernilai "Yes"
                this.delete(id);
                // this.penjemputanDao.delete(id);
                 JOptionPane.showMessageDialog(PenjemputanCRUD.this, "Data sudah dihapus", "Peringatan!", JOptionPane.WARNING_MESSAGE);
               } else { //Jika tidak,
                   JOptionPane.showMessageDialog(PenjemputanCRUD.this, "Data tidak dihapus"); 
               }
        }
    }// GEN-LAST:event_buttonHapusActionPerformed

    private void textfieldNamaKurirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textfieldNamaKurirActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textfieldNamaKurirActionPerformed

    private void textfieldNamaPelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textfieldNamaPelangganActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textfieldNamaPelangganActionPerformed

    private void textfieldAlamatPelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textfieldAlamatPelangganActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textfieldAlamatPelangganActionPerformed

    // Method untuk menambahkan penjemputan ke tableModel
    public void addData(Penjemputan penjemputan) {
        penjemputanModelTable.add(penjemputan);
        textfieldNamaPelanggan.setText("");
        textfieldAlamatPelanggan.setText("");
        radioFalse.setSelected(true);
    }

    // Method untuk mengubah penjemputan ke tableModel
    public void update(Penjemputan penjemputan) {
        penjemputanModelTable.update(penjemputan);
        textfieldNamaPelanggan.setText("");
        textfieldAlamatPelanggan.setText("");
    }

    // Method untuk menghapus penjemputan ke tableModel
    public void delete(Penjemputan penjemputan) {
        // Tambahkan penjemputan ke tableModel
        penjemputanModelTable.delete(penjemputan);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonSimpanUbah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JPanel frameCRUDPenjemputan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAlamatPelanggan;
    private javax.swing.JLabel labelAlamatTujuan;
    private javax.swing.JLabel labelNamaKurir;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel panelCRUDPenjemputan;
    private javax.swing.JRadioButton radioFalse;
    private javax.swing.JRadioButton radioTrue;
    private javax.swing.JScrollPane scrollableTable;
    private javax.swing.JTable tablePenjemputan;
    private javax.swing.JTextField textfieldAlamatPelanggan;
    private javax.swing.JTextField textfieldAlamatTujuan;
    private javax.swing.JTextField textfieldNamaKurir;
    private javax.swing.JTextField textfieldNamaPelanggan;
    private javax.swing.JLabel titleCRUDPermintaan;
    // End of variables declaration//GEN-END:variables
}
